const { test } = require('node:test');
const assert = require('node:assert/strict');
const { io } = require('socket.io-client');
const { once } = require('node:events');
const { createGameServer } = require('../lib/server');
const { MemoryStore } = require('../lib/store');
const { repository } = require('./helpers');

const emit = (socket, event, payload = {}) => socket.timeout(3000).emitWithAck(event, payload);

test('real Socket.IO clients: roles, room isolation, answers, replacement and final archive', async t => {
  const repo = repository();
  const server = await createGameServer({ store: new MemoryStore(), repository: repo, tickMs: 10000 });
  t.after(() => server.close());
  const address = await server.listen(0, '127.0.0.1');
  const connect = async (token) => {
    const socket = io(`http://127.0.0.1:${address.port}`, { transports: ['websocket'], forceNew: true, reconnection: false, auth: { accessToken: token } });
    t.after(() => socket.disconnect());
    await once(socket, 'connect');
    return socket;
  };
  const admin = await connect('valid-token');
  const intruder = await connect();
  const rejected = await emit(intruder, 'admin:create_game', { quizId: repo.data.id });
  assert.equal(rejected.error.code, 'UNAUTHORIZED');
  const created = await emit(admin, 'admin:create_game', { quizId: repo.data.id });
  assert.equal(created.ok, true);
  const { gameCode, gameId } = created.data.state;
  assert.ok(server.io.sockets.adapter.rooms.has(gameId));
  assert.ok(!server.io.sockets.adapter.rooms.has(gameCode));
  assert.equal((await emit(intruder, 'admin:join', { gameCode })).error.code, 'UNAUTHORIZED');
  const player = await connect();
  const joined = await emit(player, 'player:join', { gameCode, nickname: 'Anna' });
  assert.equal(joined.ok, true);
  const { playerId, sessionToken } = joined.data;
  assert.equal((await emit(player, 'admin:start_game', { revision: 2 })).error.code, 'FORBIDDEN');
  const screen = await connect();
  assert.equal((await emit(screen, 'presentation:join', { gameId })).ok, true);
  assert.equal((await emit(screen, 'player:answer', {})).error.code, 'FORBIDDEN');
  const otherAdmin = await connect('valid-token');
  const other = await emit(otherAdmin, 'admin:create_game', { quizId: repo.data.id });
  const outsider = await connect();
  await emit(outsider, 'presentation:join', { gameCode: other.data.state.gameCode });
  const wrongRoomEvents = [];
  outsider.on('game:state_update', state => { if (state.gameId === gameId) wrongRoomEvents.push(state); });
  const next = async event => {
    const sync = await emit(admin, 'game:sync');
    const response = await emit(admin, event, { revision: sync.data.state.revision });
    assert.equal(response.ok, true, JSON.stringify(response));
    return response;
  };
  await next('admin:start_game');
  await next('admin:next_state');
  const q = repo.data.questions[0];
  const answer = await emit(player, 'player:answer', { questionId: q.id, answerId: q.answers[0].id, nickname: 'Spoofed', timeTaken: -1, gameCode: other.data.state.gameCode });
  assert.deepEqual(answer, { ok: true, data: { answerId: q.answers[0].id } });
  assert.equal((await emit(player, 'player:answer', { questionId: q.id, answerId: q.answers[1].id })).error.code, 'ALREADY_ANSWERED');
  const newPlayer = await connect();
  const disconnected = once(player, 'disconnect');
  const resumed = await emit(newPlayer, 'player:reconnect', { gameCode, playerId, sessionToken });
  assert.equal(resumed.ok, true);
  assert.equal(resumed.data.answerId, q.answers[0].id);
  assert.equal((await emit(newPlayer, 'game:sync')).data.answerId, q.answers[0].id);
  await disconnected;
  await next('admin:next_state');
  const reveal = await next('admin:next_state');
  assert.equal(reveal.data.state.leaderboard[0].score, 100);
  const revision = (await emit(admin, 'game:sync')).data.state.revision;
  const kicked = once(newPlayer, 'player:kicked');
  assert.equal((await emit(admin, 'admin:kick_player', { revision, playerId })).ok, true);
  await kicked;
  const blocked = await connect();
  assert.equal((await emit(blocked, 'player:reconnect', { gameCode, playerId, sessionToken })).error.code, 'INVALID_SESSION');
  const ended = once(screen, 'game:ended');
  await next('admin:end_game');
  assert.equal((await ended)[0].status, 'ENDED');
  assert.equal(repo.archived.length, 1);
  assert.equal(wrongRoomEvents.length, 0);
  assert.equal((await emit(intruder, 'player:join', null)).error.code, 'INVALID_PAYLOAD');
});

test('automatic timers broadcast server deadlines and lock without admin commands', async t => {
  let time = 100000;
  const repo = repository();
  repo.data.questions[0].preview_seconds = 1;
  repo.data.questions[0].answer_seconds = 1;
  const server = await createGameServer({ store: new MemoryStore(), repository: repo, now: () => time, tickMs: 10 });
  t.after(() => server.close());
  const address = await server.listen(0, '127.0.0.1');
  const admin = io(`http://127.0.0.1:${address.port}`, { transports: ['websocket'], reconnection: false, auth: { accessToken: 'valid-token' } });
  t.after(() => admin.disconnect());
  await once(admin, 'connect');
  const created = await emit(admin, 'admin:create_game', { quizId: repo.data.id });
  const tick = once(admin, 'game:timer_update');
  const started = await emit(admin, 'admin:start_game', { revision: created.data.state.revision });
  assert.equal(started.data.state.status, 'QUESTION_PREVIEW');
  assert.equal((await tick)[0].deadline, 101000);
  let changed = once(admin, 'game:state_update');
  time = 101000;
  assert.equal((await changed)[0].status, 'QUESTION_ACTIVE');
  changed = once(admin, 'game:state_update');
  time = 102000;
  assert.equal((await changed)[0].status, 'QUESTION_LOCKED');
});
